//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kk
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Комм услуги.
    /// </summary>
    // *** Start programmer edit section *** (КоммУслуги CustomAttributes)

    // *** End programmer edit section *** (КоммУслуги CustomAttributes)
    public enum КоммУслуги
    {
        
        // *** Start programmer edit section *** (КоммУслуги.ВывозМусора CustomAttributes)

        // *** End programmer edit section *** (КоммУслуги.ВывозМусора CustomAttributes)
        ВывозМусора,
        
        // *** Start programmer edit section *** (КоммУслуги.Отопление CustomAttributes)

        // *** End programmer edit section *** (КоммУслуги.Отопление CustomAttributes)
        Отопление,
        
        // *** Start programmer edit section *** (КоммУслуги.ТекущийРемонт CustomAttributes)

        // *** End programmer edit section *** (КоммУслуги.ТекущийРемонт CustomAttributes)
        ТекущийРемонт,
        
        // *** Start programmer edit section *** (КоммУслуги.Электроэнергия CustomAttributes)

        // *** End programmer edit section *** (КоммУслуги.Электроэнергия CustomAttributes)
        Электроэнергия,
        
        // *** Start programmer edit section *** (КоммУслуги.Вода CustomAttributes)

        // *** End programmer edit section *** (КоммУслуги.Вода CustomAttributes)
        Вода,
        
        // *** Start programmer edit section *** (КоммУслуги.КапитальныйРемонт CustomAttributes)

        // *** End programmer edit section *** (КоммУслуги.КапитальныйРемонт CustomAttributes)
        КапитальныйРемонт,
        
        // *** Start programmer edit section *** (КоммУслуги.Газоснабжение CustomAttributes)

        // *** End programmer edit section *** (КоммУслуги.Газоснабжение CustomAttributes)
        Газоснабжение,
        
        // *** Start programmer edit section *** (КоммУслуги.Водоотведение CustomAttributes)

        // *** End programmer edit section *** (КоммУслуги.Водоотведение CustomAttributes)
        Водоотведение,
    }
}
