//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kk
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тариф.
    /// </summary>
    // *** Start programmer edit section *** (Тариф CustomAttributes)

    // *** End programmer edit section *** (Тариф CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТарифE", new string[] {
            "IDтарифа as \'I dтарифа\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    [View("ТарифL", new string[] {
            "IDтарифа as \'I dтарифа\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    public class Тариф : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDтарифа;
        
        private IIS.Kk.КоммУслуги fНаименование;
        
        private int fСтоимость;
        
        // *** Start programmer edit section *** (Тариф CustomMembers)

        // *** End programmer edit section *** (Тариф CustomMembers)

        
        /// <summary>
        /// IDтарифа.
        /// </summary>
        // *** Start programmer edit section *** (Тариф.IDтарифа CustomAttributes)

        // *** End programmer edit section *** (Тариф.IDтарифа CustomAttributes)
        public virtual int IDтарифа
        {
            get
            {
                // *** Start programmer edit section *** (Тариф.IDтарифа Get start)

                // *** End programmer edit section *** (Тариф.IDтарифа Get start)
                int result = this.fIDтарифа;
                // *** Start programmer edit section *** (Тариф.IDтарифа Get end)

                // *** End programmer edit section *** (Тариф.IDтарифа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тариф.IDтарифа Set start)

                // *** End programmer edit section *** (Тариф.IDтарифа Set start)
                this.fIDтарифа = value;
                // *** Start programmer edit section *** (Тариф.IDтарифа Set end)

                // *** End programmer edit section *** (Тариф.IDтарифа Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Тариф.Наименование CustomAttributes)

        // *** End programmer edit section *** (Тариф.Наименование CustomAttributes)
        public virtual IIS.Kk.КоммУслуги Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Тариф.Наименование Get start)

                // *** End programmer edit section *** (Тариф.Наименование Get start)
                IIS.Kk.КоммУслуги result = this.fНаименование;
                // *** Start programmer edit section *** (Тариф.Наименование Get end)

                // *** End programmer edit section *** (Тариф.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тариф.Наименование Set start)

                // *** End programmer edit section *** (Тариф.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Тариф.Наименование Set end)

                // *** End programmer edit section *** (Тариф.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Тариф.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Тариф.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Тариф.Стоимость Get start)

                // *** End programmer edit section *** (Тариф.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (Тариф.Стоимость Get end)

                // *** End programmer edit section *** (Тариф.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тариф.Стоимость Set start)

                // *** End programmer edit section *** (Тариф.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Тариф.Стоимость Set end)

                // *** End programmer edit section *** (Тариф.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТарифE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТарифE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТарифE", typeof(IIS.Kk.Тариф));
                }
            }
            
            /// <summary>
            /// "ТарифL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТарифL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТарифL", typeof(IIS.Kk.Тариф));
                }
            }
        }
    }
}
