//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kk
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч перерасчета КУ.
    /// </summary>
    // *** Start programmer edit section *** (ТЧПерерасчетаКУ CustomAttributes)

    // *** End programmer edit section *** (ТЧПерерасчетаКУ CustomAttributes)
    [AutoAltered()]
    [Caption("Табличная часть перерасчета коммунальных услуг")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧПерерасчетаКУE", new string[] {
            "Услуга as \'Услуга\'"})]
    public class ТЧПерерасчетаКУ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЛицСчет;
        
        private System.DateTime fМесяцНачис;
        
        private IIS.Kk.КоммУслуги fУслуга;
        
        private int fСуммаНачис;
        
        private string fТипНачис;
        
        private int fСуммаКоррек;
        
        private IIS.Kk.БазаДанныхЛС fБазаДанныхЛС;
        
        private IIS.Kk.ПерерасчетКУ fПерерасчетКУ;
        
        // *** Start programmer edit section *** (ТЧПерерасчетаКУ CustomMembers)

        // *** End programmer edit section *** (ТЧПерерасчетаКУ CustomMembers)

        
        /// <summary>
        /// МесяцНачис.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис CustomAttributes)

        // *** End programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис CustomAttributes)
        public virtual System.DateTime МесяцНачис
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис Get start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис Get start)
                System.DateTime result = this.fМесяцНачис;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис Get end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис Set start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис Set start)
                this.fМесяцНачис = value;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис Set end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.МесяцНачис Set end)
            }
        }
        
        /// <summary>
        /// НомерЛицСчет.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет CustomAttributes)

        // *** End programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет CustomAttributes)
        public virtual int НомерЛицСчет
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет Get start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет Get start)
                int result = this.fНомерЛицСчет;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет Get end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет Set start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет Set start)
                this.fНомерЛицСчет = value;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет Set end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.НомерЛицСчет Set end)
            }
        }
        
        /// <summary>
        /// СуммаКоррек.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек CustomAttributes)

        // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек CustomAttributes)
        public virtual int СуммаКоррек
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек Get start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек Get start)
                int result = this.fСуммаКоррек;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек Get end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек Set start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек Set start)
                this.fСуммаКоррек = value;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек Set end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаКоррек Set end)
            }
        }
        
        /// <summary>
        /// СуммаНачис.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис CustomAttributes)

        // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис CustomAttributes)
        public virtual int СуммаНачис
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис Get start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис Get start)
                int result = this.fСуммаНачис;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис Get end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис Set start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис Set start)
                this.fСуммаНачис = value;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис Set end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.СуммаНачис Set end)
            }
        }
        
        /// <summary>
        /// ТипНачис.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис CustomAttributes)

        // *** End programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис CustomAttributes)
        [StrLen(255)]
        public virtual string ТипНачис
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис Get start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис Get start)
                string result = this.fТипНачис;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис Get end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис Set start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис Set start)
                this.fТипНачис = value;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис Set end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.ТипНачис Set end)
            }
        }
        
        /// <summary>
        /// Услуга.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПерерасчетаКУ.Услуга CustomAttributes)

        // *** End programmer edit section *** (ТЧПерерасчетаКУ.Услуга CustomAttributes)
        public virtual IIS.Kk.КоммУслуги Услуга
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.Услуга Get start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.Услуга Get start)
                IIS.Kk.КоммУслуги result = this.fУслуга;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.Услуга Get end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.Услуга Set start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.Услуга Set end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.Услуга Set end)
            }
        }
        
        /// <summary>
        /// Т ч перерасчета КУ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС CustomAttributes)

        // *** End programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС CustomAttributes)
        [PropertyStorage(new string[] {
                "БазаДанныхЛС"})]
        [NotNull()]
        public virtual IIS.Kk.БазаДанныхЛС БазаДанныхЛС
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС Get start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС Get start)
                IIS.Kk.БазаДанныхЛС result = this.fБазаДанныхЛС;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС Get end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС Set start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС Set start)
                this.fБазаДанныхЛС = value;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС Set end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.БазаДанныхЛС Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kk.ПерерасчетКУ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ CustomAttributes)

        // *** End programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПерерасчетКУ"})]
        public virtual IIS.Kk.ПерерасчетКУ ПерерасчетКУ
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ Get start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ Get start)
                IIS.Kk.ПерерасчетКУ result = this.fПерерасчетКУ;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ Get end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ Set start)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ Set start)
                this.fПерерасчетКУ = value;
                // *** Start programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ Set end)

                // *** End programmer edit section *** (ТЧПерерасчетаКУ.ПерерасчетКУ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧПерерасчетаКУE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧПерерасчетаКУE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧПерерасчетаКУE", typeof(IIS.Kk.ТЧПерерасчетаКУ));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧПерерасчетаКУ.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧПерерасчетаКУ CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧПерерасчетаКУ CustomAttributes)
    public class DetailArrayOfТЧПерерасчетаКУ : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kk.DetailArrayOfТЧПерерасчетаКУ members)

        // *** End programmer edit section *** (IIS.Kk.DetailArrayOfТЧПерерасчетаКУ members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧПерерасчетаКУ by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧПерерасчетаКУ.
        /// </summary>
        public DetailArrayOfТЧПерерасчетаКУ(IIS.Kk.ПерерасчетКУ fПерерасчетКУ) : 
                base(typeof(ТЧПерерасчетаКУ), ((ICSSoft.STORMNET.DataObject)(fПерерасчетКУ)))
        {
        }
        
        public IIS.Kk.ТЧПерерасчетаКУ this[int index]
        {
            get
            {
                return ((IIS.Kk.ТЧПерерасчетаКУ)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kk.ТЧПерерасчетаКУ dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
